AWSTemplateFormatVersion: 2010-09-09
Description: EC2 instance 

Parameters:
  GitCommit:
    Type: String

Resources:
  SinatraLaunchConfiguration: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      ImageId: ami-08fdde86b93accf1c
      InstanceType: t3.small
      UserData: |
        sudo yum install ruby -y
        sudo yum install git -y
        sudo sudo yum install git-core zlib zlib-devel gcc-c++ patch readline readline-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison curl sqlite-devel -y
        sudo curl -sL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash -
        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(rbenv init -)"' >> ~/.bashrc
        source ~/.bashrc
        
        sudo rbenv install 2.5.1
        sudo rbenv global 2.5.1
        sudo gem install bundler

  SinatraAppAutoScaling: 
    UpdatePolicy: 
      AutoScalingRollingUpdate: 
        MinInstancesInService: 1
        MaxBatchSize: 1
        PauseTime: "PT15M"
        WaitOnResourceSignals: True
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AvailabilityZones: 
        Fn::GetAZs: 
          Ref: "AWS::Region"
      LaunchConfigurationName: !Ref SinatraLaunchConfiguration
      MaxSize: "3"
      MinSize: "1"